name: gen2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.12.0=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.4.0=h27087fc_1
  - backports.zstd=1.2.0=py310h69bd2ac_0
  - blas=1.0=mkl
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.1.80=h3b4bcfc_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.1=hd92462c_3
  - dataclasses=0.8=pyhc8e2a94_3
  - distro=1.9.0=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - ffmpeg=4.4.2=gpl_h45a1190_107
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.7.6=he274497_3
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.1=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jiter=0.12.0=py310hdfeec95_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.16.0.49=h3b4bcfc_0
  - libcurand=10.4.1.34=h5dabb87_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=13.1.80=h6205011_0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_2
  - libsentencepiece=0.2.1=h1d72405_1
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=h5347b49_1
  - libva=2.23.0=he1eb515_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.9=h04c0eec_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.8.1=hc379101_1
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - openai=2.11.0=pyhd8ed1ab_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.3.0=h27087fc_0
  - openpyxl=3.1.5=py310h05b0c27_2
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_2
  - pip=25.3=pyh8b19718_0
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py310hd8f68c5_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.19=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.2=h8c095d6_2
  - regex=2025.11.3=py310h7c4b9e2_1
  - requests=2.32.5=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.7.0=py310hdfeec95_0
  - scipy=1.15.2=py310h1d65ade_0
  - sentencepiece=0.2.1=hc5512b6_1
  - sentencepiece-python=0.2.1=py310h1469a80_1
  - sentencepiece-spm=0.2.1=h1d72405_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - svt-av1=1.2.0=h27087fc_0
  - sympy=1.14.0=pyh2585a3b_105
  - tk=8.6.13=noxft_ha0e22de_103
  - tokenizers=0.22.2=py310h4551fc8_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - anthropic==0.71.0
      - apache-tvm-ffi==0.1.6
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.49.0
      - blake3==1.0.8
      - cachetools==6.2.4
      - cbor2==5.7.1
      - click==8.2.1
      - cloudpickle==3.1.2
      - compressed-tensors==0.12.2
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - fastapi==0.124.4
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.7.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - flashinfer-python==0.5.2
      - frozenlist==1.8.0
      - gguf==0.17.1
      - httptools==0.7.1
      - huggingface-hub==0.36.0
      - interegular==0.3.3
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - model-hosting-container-standards==0.1.12
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - ninja==1.13.0
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.3
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.11
      - partial-json-parser==0.2.1.1.post7
      - pillow==12.0.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - py-cpuinfo==9.0.0
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pydantic-extra-types==2.10.6
      - pygments==2.19.2
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pyzmq==27.1.0
      - ray==2.52.1
      - referencing==0.37.0
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - sentry-sdk==2.48.0
      - setproctitle==1.3.7
      - starlette==0.50.0
      - supervisor==4.3.0
      - tabulate==0.9.0
      - tiktoken==0.12.0
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - transformers==4.57.3
      - triton==3.5.0
      - typer==0.20.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.11.2
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - yarl==1.22.0
prefix: /seu_share2/home/dishimin/230259983/Anaconda/envs/gen
